### ISSUE TITLE
maximum limit of spotify track_id inquiries from spotipy per query

### ISSUE THREAD

**Issue by CrawFishFiesta** [plamere/spotipy#160]
Hello,

Does anyone know what the limit of track id's that can't be sent through spotipy/spotify API?

I have a list of ~150 spotipy track id's that I tried feeding through spotipy, but the error below saying that I've requested too many ids.

Is there a way around this?

Thanks a lot.

```
C:\Users>python2 spotifyMulti
pleTracksFromCSV.py
Traceback (most recent call last):
  File "spotifyMultipleTracksFromCSV.py", line 29, in <module>
    results = spotify.tracks({strOfTrackIds})
  File "C:\Python27\lib\site-packages\spotipy\client.py", line 219, in tracks
    return self._get('tracks/?ids=' + ','.join(tlist))
  File "C:\Python27\lib\site-packages\spotipy\client.py", line 133, in _get
    return self._internal_call('GET', url, payload, kwargs)
  File "C:\Python27\lib\site-packages\spotipy\client.py", line 111, in _internal
_call
    -1, '%s:\n %s' % (r.url, r.json()['error']['message']))
spotipy.client.SpotifyException: http status: 400, code:-1 - https://api.spotify
.com/v1/tracks/?ids=0aIIMF4tzxil3kucPwc2wK,4Pb1vhZi5DsqBLikqaxFEL,07Tx168RSsUS1H
qkDIOZbH,3pqEVPtR5nl71DJ9EiWgmQ,60qnlDxdXkgcDAwBdRoRQP,6VNnM2Qlow95xRDBXfoy50,7t
cas5SzlIDMgTepFemx9e,5XNm6WTJxKtcaug3lc8KJF,7EVG8LgkxwLcMskvF6VVZy,7EVG8LgkxwLcM
skvF6VVZy,5TklECQ3x2MybRjaeIsTlm,60qnlDxdXkgcDAwBdRoRQP,3HxdXrWAAgK4a53m3lajPA,4
u4t9R8Iky417ZasENaKXX,3FmywdJ21ffovLTqQlY7xr,5XNm6WTJxKtcaug3lc8KJF,6cFqMHDH8BBW
UGvghxBSdk,0KVF0f32xUa86fFPaqytwJ,3FmywdJ21ffovLTqQlY7xr,4Pb1vhZi5DsqBLikqaxFEL,
39YIK5rTuhfFlqWN6zMkoC,0aIIMF4tzxil3kucPwc2wK,5Q9MCK4NU3xApjsIkKWegw,1IvPBp0jFds
jdi4bbQw719,4WxjlZbzLsAqGwr2i6Sq7E,4nH0DYzmr6rIicg8PnSlnk,3pqEVPtR5nl71DJ9EiWgmQ
,3pqEVPtR5nl71DJ9EiWgmQ,11KJSRSgaDxqydKYiD2Jew,7v7r7iT4INJjDbdHNVEU1c,6lKpgB0mqI
68SXmnjSrEjS,6cFqMHDH8BBWUGvghxBSdk,4GDX3ZlA4VbVHGT75TQ1uW,1lItf5ZXJc1by9SbPeljF
d,7juAP7GZBF0Dtm0qqLSWOJ,4GDX3ZlA4VbVHGT75TQ1uW,3JvKfv6T31zO0ini8iNItO,0Uh6KAHee
EqBopLbtzRirI,6PaGForx8vjTY0yu9THgzX,6cFqMHDH8BBWUGvghxBSdk,6g6TC8NLcWAuzQP3XSLP
ky,6lKpgB0mqI68SXmnjSrEjS,73scFnG9NKXzXyeSJ6WwxF,6PaGForx8vjTY0yu9THgzX,2czeogK7
hI7NElf3bNhsor,7MbiqFLnw44ZrQCbF6fmrW,3HxdXrWAAgK4a53m3lajPA,4nH0DYzmr6rIicg8PnS
lnk,60qnlDxdXkgcDAwBdRoRQP,0aIIMF4tzxil3kucPwc2wK,2czeogK7hI7NElf3bNhsor,6lKpgB0
mqI68SXmnjSrEjS,3pqEVPtR5nl71DJ9EiWgmQ,4nH0DYzmr6rIicg8PnSlnk,0aIIMF4tzxil3kucPw
c2wK,3HxdXrWAAgK4a53m3lajPA,3folt4d0CndACKo02YNrin,39YIK5rTuhfFlqWN6zMkoC,1tNQEE
oJ90f8welgLXPEw4,4WxjlZbzLsAqGwr2i6Sq7E,1B1q0y2reBKW7SKMo73iFF,3pqEVPtR5nl71DJ9E
iWgmQ,39YIK5rTuhfFlqWN6zMkoC,1xFpp6uYNRPHfNe2M4gguQ,6Gr0KCTprJAhCpzjAw6xyE,0aIIM
F4tzxil3kucPwc2wK,0aIIMF4tzxil3kucPwc2wK,5wQTS8buORezHxMK8cHOoV,1xFpp6uYNRPHfNe2
M4gguQ,4LsfkIMT7DXjzbq4HlKZ4p,5wQTS8buORezHxMK8cHOoV,1xFpp6uYNRPHfNe2M4gguQ,5P4Y
rV968ejQHeRf1l8hDE,39YIK5rTuhfFlqWN6zMkoC,7EVG8LgkxwLcMskvF6VVZy,6PaGForx8vjTY0y
u9THgzX,6tLu63a1IW4auXuHDGy4n5,6fujklziTHa8uoM5OQSfIo,4Pb1vhZi5DsqBLikqaxFEL,1xF
pp6uYNRPHfNe2M4gguQ,3pqEVPtR5nl71DJ9EiWgmQ,3pqEVPtR5nl71DJ9EiWgmQ,5wQTS8buORezHx
MK8cHOoV,5vrMJjqybyZcvnY1RNpwiC,5PsyuOkRJ1EjvwjtTGJdvt,4t53p6qK1JK00OIqCYGlxX,4G
DX3ZlA4VbVHGT75TQ1uW,1xFpp6uYNRPHfNe2M4gguQ,7MbiqFLnw44ZrQCbF6fmrW,7MbiqFLnw44Zr
QCbF6fmrW,38IckGSLq1mQub6NOwsKMP,39YIK5rTuhfFlqWN6zMkoC,6Gr0KCTprJAhCpzjAw6xyE,6
0qnlDxdXkgcDAwBdRoRQP,66iipPIorFQPk2YIM7Xbt2,4B3qvzOMzLQXLeYgPsG3KA,6lKpgB0mqI68
SXmnjSrEjS,7EVG8LgkxwLcMskvF6VVZy,3folt4d0CndACKo02YNrin,3JkJnBHeF7YWq3EW33hWdF,
4GDX3ZlA4VbVHGT75TQ1uW,0aIIMF4tzxil3kucPwc2wK,3HxdXrWAAgK4a53m3lajPA,2czeogK7hI7
NElf3bNhsor,2kWfO7rKJk3qFacoFW26nk,60qnlDxdXkgcDAwBdRoRQP,4nH0DYzmr6rIicg8PnSlnk
,4GDX3ZlA4VbVHGT75TQ1uW,4TDoUr2meaXsfbPFMdrqOE,1xFpp6uYNRPHfNe2M4gguQ,5wQTS8buOR
ezHxMK8cHOoV,4nH0DYzmr6rIicg8PnSlnk,39YIK5rTuhfFlqWN6zMkoC,60qnlDxdXkgcDAwBdRoRQ
P,3buZNBqLqmrcCZuJZbtRUD,6cFqMHDH8BBWUGvghxBSdk,4w2iAP3X4FkpPb5kjRdIDx,3i01M7jnv
BYrhG6YnAqCdC,4Pb1vhZi5DsqBLikqaxFEL,4GDX3ZlA4VbVHGT75TQ1uW,4t53p6qK1JK00OIqCYGl
xX,4GDX3ZlA4VbVHGT75TQ1uW,3TObBPe3nHX51mqOIHV84W,4Pb1vhZi5DsqBLikqaxFEL,4nH0DYzm
r6rIicg8PnSlnk,4nH0DYzmr6rIicg8PnSlnk,4B3qvzOMzLQXLeYgPsG3KA,0aIIMF4tzxil3kucPwc
2wK,7v7r7iT4INJjDbdHNVEU1c,7v7r7iT4INJjDbdHNVEU1c,1xFpp6uYNRPHfNe2M4gguQ,39YIK5r
TuhfFlqWN6zMkoC,2HBlo99yKt2d6WVSVM5UvU,5wQTS8buORezHxMK8cHOoV,0KVF0f32xUa86fFPaq
ytwJ,5PsyuOkRJ1EjvwjtTGJdvt,0Uh6KAHeeEqBopLbtzRirI,5wQTS8buORezHxMK8cHOoV,2czeog
K7hI7NElf3bNhsor,4GDX3ZlA4VbVHGT75TQ1uW,6lKpgB0mqI68SXmnjSrEjS,4TDoUr2meaXsfbPFM
drqOE,5fdzPMOxUqVJYSzTP5cFP7,5MEYDJVJMaGAXfddTo0D6J,66iipPIorFQPk2YIM7Xbt2,7v7r7
iT4INJjDbdHNVEU1c,5PsUB0ISfQxRLhF5DmI5Ks,38IckGSLq1mQub6NOwsKMP,5vrMJjqybyZcvnY1
RNpwiC,3KuZx7FPNcqXG8YFN5Y0OG,4TDoUr2meaXsfbPFMdrqOE,4nH0DYzmr6rIicg8PnSlnk:
 too many ids requested
```

**Comment by CrawFishFiesta** [comment]
It seems like the track_id limit per spotify API request is 50 tracks.  I broke up my data set (152 track_id's) into 4 smaller data sets and was able to decode the information.

If anyone has any idea on any type of limits with spotify API please let me know.

In addition, if anyone knows a better way around this other than breaking up the data set into smaller groups, please let me know as well.

Thanks.

**Comment by stephanebruckert** [comment]
Doc just updated accordingly.

@CrawFishFiesta  see if this helps https://stackoverflow.com/a/312464/1515819
