### ISSUE TITLE
Invalid calls to logging method

### ISSUE THREAD

**Issue by kellcomnet2** [plamere/spotipy#367]
Versions:

    spotipy in /usr/local/lib/python3.5/dist-packages (2.4.4)
    requests>=1.0 in /usr/lib/python3/dist-packages (from spotipy) (2.21.0)

Error

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/spotdl/downloader.py", line 207, in _download_list
        track_dl = Downloader(raw_song, number=number)
      File "/usr/local/lib/python3.5/dist-packages/spotdl/downloader.py", line 98, in __init__
        self.content, self.meta_tags = youtube_tools.match_video_and_metadata(raw_song)
      File "/usr/local/lib/python3.5/dist-packages/spotdl/youtube_tools.py", line 76, in match_video_and_metadata
        meta_tags = spotify_tools.generate_metadata(track)
      File "/usr/local/lib/python3.5/dist-packages/spotdl/spotify_tools.py", line 34, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/spotdl/spotify_tools.py", line 48, in generate_metadata
        meta_tags = spotify.track(raw_song)
      File "/usr/local/lib/python3.5/dist-packages/spotipy/client.py", line 222, in track
        trid = self._get_id('track', track_id)
      File "/usr/local/lib/python3.5/dist-packages/spotipy/client.py", line 850, in _get_id
        type, fields[-2], id)
    TypeError: _warn() takes 2 positional arguments but 5 were given

**Comment by NotFunnyMan** [comment]
Nothing is clear from the data you provided. You would at least give the source code where the error occurs and what data you pass to the method that crashes.

**Comment by stephanebruckert** [comment]
Looks like the user is using another app called spotdl, which is not calling spotipy correctly. Closing but feel free to reopen with more specific information

**Comment by ritiek** [comment]
@stephanebruckert This issue is valid. #297 fixes this.

**Comment by stephanebruckert** [comment]
Indeed... nice catch. I skim-read the stacktrace.

**Comment by ritiek** [comment]
No worries! The traceback alone can indeed be confusing.

**Comment by stephanebruckert** [comment]
Fixed by https://github.com/plamere/spotipy/pull/371
