### ISSUE TITLE
spotipy.client.SpotifyException: http status: 400, code:-1 - Malformed json when trying to use start_playback with parameters

### ISSUE THREAD

**Issue by shillshocked** [plamere/spotipy#385]
Traceback (most recent call last):
  File "test.py", line 115, in <module>
    test = sp.start_playback(device_id = devs['devices'][0]['id'], context_uri = ["spotify:album:01cbQN8LXD53sEV31mpARQ"], uris = None, offset = {"uri": "spotify:track:6M6MC6OgvXBj9YnLjnJ1RF"})
  File "/usr/lib/python2.7/site-packages/spotipy/client.py", line 948, in start_playback
    return self._put(self._append_device_id("me/player/play", device_id), payload=data)
  File "/usr/lib/python2.7/site-packages/spotipy/client.py", line 190, in _put
    return self._internal_call('PUT', url, payload, kwargs)
  File "/usr/lib/python2.7/site-packages/spotipy/client.py", line 126, in _internal_call
    headers=r.headers)
spotipy.client.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=5d81cefb30a59997f5dcd7af0548f3a1b0fc1935c3:
 Malformed json

**Comment by shillshocked** [comment]
Ah, I had to upgrade librespot. It was a bug in the older version.
