### ISSUE TITLE
Enter the URL you were redirected to: <class 'EOFError'> 

### ISSUE THREAD

**Issue by bpezzullo** [plamere/spotipy#632]
I am working on moving a small app using spotipy to Heruko.  If is a flask based app and I am able to have it work when hosted on my machine.  When I push it to Heroku I get this error and figure it has something to do with my redirect URI, but can't figure it out.

2021-01-02T16:58:54.820818+00:00 app[web.1]: Enter the URL you were redirected to: <class 'EOFError'>
2021-01-02T16:58:54.820865+00:00 app[web.1]: EOF when reading a line

The code I am using is

        sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope,
                                                        client_id=CLIENT_ID,
                                                        client_secret=CLIENT_SECRET,
                                                        redirect_uri=REDIRECT_URI,
                                                        username = user))

where the REDIRET_URI is set to https://127.0.0.1:8080.  I have tried https://top100-search.herokuapp.com/redirect but can't figure out what is happening.  

Any thoughts would be helpful.

Thanks

**Comment by Peter-Schorn** [comment]
You are getting an error because spotipy is attempting to read from standard input, which probably isn't supported in the environment that the app is running in (I've never used Heruko, so I can't confirm this).

**Comment by bpezzullo** [comment]
Thanks,  I ended up re-configuring a few things and have been able to get the basics working.  I appreciate the response. Regards,-Bill From: Peter SchornSent: Saturday, January 2, 2021 5:28 PMTo: plamere/spotipyCc: Bill Pezzullo; AuthorSubject: Re: [plamere/spotipy] Enter the URL you were redirected to: <class 'EOFError'> (#632) You are getting an error because spotipy is attempting to read from standard input, which probably isn't supported in the environment that the app is running in (I've never used Heruko, so I can't confirm this).—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by forkbabu** [comment]
@Peter-Schorn so colab also would cause the same problem. Based on this article https://medium.com/@kshitijvijay271199/flask-on-google-colab-f6525986797b , do you think making the small tweak in examples/app.py would do the trick?

**Comment by Peter-Schorn** [comment]
@forkbabu Please be more specific

**Comment by ArtemKuznetsovv** [comment]
@bpezzullo Would you mind please sharing the solution for this, as I'm struggling with this as well.

**Comment by JosephJHowlett** [comment]
@bpezzullo me too, please share! thanks!

**Comment by jtyson728** [comment]
Hi I am also getting this same issue, and not sure how to resolve based on the example @Peter-Schorn posted. @bpezzullo would you be able to share what you had to reconfigure?

**Comment by stephanebruckert** [comment]
@jtyson728 so we can help please share a minimal reproducible code example, and info about your environment, as well as where you are deploying

**Comment by jtyson728** [comment]
`
from spotipy.oauth2 import SpotifyOAuth
spotify_client_id = os.environ['SPOTIPY_CLIENT_ID']
spotify_client_secret = os.environ['SPOTIPY_CLIENT_SECRET']
scope = "playlist-modify-public user-library-read user-modify-playback-state"
redirect_uri = os.environ['SPOTIPY_REDIRECT_URI']
spotify_username = os.environ['SPOT_USERNAME']
# puts credentials for account into SpotifyOAuth and initiate spotify connection instance
spot_token=SpotifyOAuth(username=spotify_username,client_id=spotify_client_id,
                        client_secret=spotify_client_secret,
                        redirect_uri=redirect_uri,
                        scope=scope,
                        show_dialog=True)
sp = spotipy.Spotify(auth_manager=spot_token)
`
I am running this from a python program, bot.py.  Recently, I deployed this to Heroku hosting platform, and added environment variables to spotify client id, secret, redirect_uri, and spotify username into Heroku environment. 

The problem is when you first connect via oAuth, running on my local I remember it redirecting to a browser page to authorize sign in, and then prompting in terminal "Enter the URL you were redirected to:". The problem is in Heroku, it is not starting this authorization flow. 

The redirect URI is set to https://lacreme-bot.herokuapp.com/callback in both the Spotify application and in environment variables.
Error output below
![Error Output](https://user-images.githubusercontent.com/36560320/144672561-517872bb-56e9-46c5-8bb2-3f6608c879e0.PNG)

**Comment by stephanebruckert** [comment]
@jtyson728 this is expected as Heroku isn't a terminal like you have on your computer, so it won't be able to redirect or let you input the resulting URL. Therefore you'll have to generate your personal token locally and pass it to Heroku as an environment variable:

    sp = spotipy.Spotify(auth=os.environ['SPOTIFY_TOKEN'])

[https://spotipy.readthedocs.io/en/2.19.0/#spotipy.client.Spotify.__init__](https://spotipy.readthedocs.io/en/2.19.0/#spotipy.client.Spotify.__init__)

This will work if the token age isn't older than 1hr, however it won't be able to refresh it as it is currently the case locally. To retrieve a long-lived token (lasts more than a year I think), you could instead get a token following https://github.com/enriquegh/spotify-webplayer-token

------

However a better way to solve this is to use an appropriate CacheHandler. Instead of the default `FileCacheHandler`, you could use `MemoryCacheHandler` so Heroku doesn't look for the token on its filesystem:

```
spot_token=SpotifyOAuth(username=spotify_username,
                        client_id=spotify_client_id,
                        client_secret=spotify_client_secret,
                        redirect_uri=redirect_uri,
                        scope=scope,
                        show_dialog=False, # Make this False or just remove the line so it doesn't open a browser
                        cache_handler=MemoryCacheHandler(
                             token_info=TOKEN_INFO
                        ))
```

To know what `TOKEN_INFO` should look like, print it using `spot_token.get_access_token()` locally and pass it as an ENV in Heroku.

https://spotipy.readthedocs.io/en/2.19.0/?highlight=cache#customized-token-caching

I agree documentation should be improved on this front, so feel free to update us where it blocks and we'll help.

**Comment by jtyson728** [comment]
This has been excellent help!! I tried the 1st method (https://github.com/enriquegh/spotify-webplayer-token), however that token seems to be expiring after an hour. I believe I might've done something wrong grabbing the cookies.

Nevertheless, I would rather implement the `MemoryCacheHandler` solution anyways. When I add in:
```
cache_handler=MemoryCacheHandler(token_info=TOKEN_INFO)
```
it says that
```
Traceback (most recent call last):
  File "C:\Users\Jeremy Tyson\Desktop\laCreme-bot\bot.py", line 52, in <module>
    cache_handler=MemoryCacheHandler(token_info=spot_token_info))
NameError: name 'MemoryCacheHandler' is not defined
```
Is there another example of the MemoryCacheHandler that I can see, my apologies I might just be using it wrong! :/

**Comment by stephanebruckert** [comment]
Make sure you upgrade to 2.19 

    pip install spotipy --upgrade

**Comment by jtyson728** [comment]
Hi so I upgraded to latest version, unfortunately I am still geting EOFError when I start up the app on Heroku. Here is what I did:
1. Print the access token of the SpotifyOAuth spot_token locally, and then pass that into environment variable in my Heroku settings.
```
spot_token=SpotifyOAuth(username=spotify_username,client_id=spotify_client_id,
                        client_secret=spotify_client_secret,
                        redirect_uri=redirect_uri,
                        scope=scope)
print(f'This is access token----> {spot_token.get_access_token(as_dict=False)}')    #copied this token value to heroku
```
2. Added Memory cache handler to spotifyOAuth object that takes in stored access token from local run into Heroku code
```
cache_handler = spotipy.cache_handler.MemoryCacheHandler(token_info=spot_token_info)
spot_token=SpotifyOAuth(username=spotify_username,client_id=spotify_client_id,
                        client_secret=spotify_client_secret,
                        redirect_uri=redirect_uri,
                        scope=scope,
                        cache_handler=cache_handler)
sp = spotipy.Spotify(auth_manager=spot_token, requests_timeout=15, retries=10)
```
3. Ran app via Heroku, noticed in logs that it is still trying to read the redirect url from input.
```
2021-12-27T17:51:44.313820+00:00 app[worker.1]: Enter the URL you were redirected to: Unhandled exception in internal background task 'clear_weekly'.
```

I'm not exactly sure how avoid the redirect URL aspect while still using the SpotifyOAuth auth_manager flow, or what part exactly is messing it up. 

Also added update, the 1-year spotify access token retrieved using  https://github.com/enriquegh/spotify-webplayer-token is only lasting for 1 hour, and then expiring. I have posted this as an issue to his git repo, no response yet.

**Comment by Peter-Schorn** [comment]
@jtyson728 `MemoryCacheHandler`, as well as all the other cache handlers, need more than just the access token. They need a dictionary that contains the access token, expiration date, and, optionally, the refresh token and scopes. Go through the authorization process again locally using `MemoryCacheHandler`. Then print the `MemoryCacheHandler.token_info` instance property. You will see that it is a dictionary containing the aforementioned properties. You need to pass this same value back into the initializer for `MemoryCacheHandler`.

**Comment by Addimator** [comment]
My problem is now, that it is not possible to do this for different users in the app (via login), since one needs a new access token every time. Has anyone an idea how to deal with this problem?

**Comment by bpezzullo** [comment]
I haven’t followed what you are trying to do, but I ask the user to log into Spotify every time they start up the App.  Then they can transfer a playlist that they created from a set of top 100 songs over the years than I have.  They can’t play the songs.

 

Not sure if that helps.

**Comment by Addimator** [comment]
But how do you do the authentification then? Doesn't it redirect you to your redirect URL and than throws the error described above?

**Comment by Zhiming77** [comment]
I solved the initial EOFError that brought me here, using the following code:

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id=client_id,
                                                 client_secret=client_secret,
                                                 redirect_uri=redirect_uri,
                                                 scope=scope,
                                                show_dialog=False,
                                               open_browser=False,
                                               cache_handler=MemoryCacheHandler(token_info=token_info)
                                               ).get_access_token(as_dict=True, check_cache=True))

The bot is "successfully" hosted on Heroku, and I can use commands that don't access the Spotify API.
However, now when I try to access the API in any manner, for example, playlists = sp.current_user_playlists()

I get the following error:

2023-07-12T12:29:03.090777+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/spotipy/client.py", line 338, in _put
2023-07-12T12:29:03.090777+00:00 app[web.1]:     return self._internal_call("PUT", url, payload, kwargs)
2023-07-12T12:29:03.090777+00:00 app[web.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-12T12:29:03.090778+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/spotipy/client.py", line 247, in _internal_call
2023-07-12T12:29:03.090778+00:00 app[web.1]:     headers = self._auth_headers()
2023-07-12T12:29:03.090778+00:00 app[web.1]:               ^^^^^^^^^^^^^^^^^^^^
2023-07-12T12:29:03.090778+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/spotipy/client.py", line 238, in _auth_headers
2023-07-12T12:29:03.090779+00:00 app[web.1]:     token = self.auth_manager.get_access_token(as_dict=False)
2023-07-12T12:29:03.090779+00:00 app[web.1]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-12T12:29:03.090780+00:00 app[web.1]: AttributeError: 'dict' object has no attribute 'get_access_token'

Why is self.auth_manager appearing as a dictionary herein (it would seem based on the spotipy code that it should not be appearing as a dictionary)?

Thank you for any and all assistance. It's really making my head spin!
