### ISSUE TITLE
Permissions missing, reason: None

### ISSUE THREAD

**Issue by joebonneau** [plamere/spotipy#657]
Hello there,

I am trying to run the following block of code:

> import spotipy
> from spotipy.oauth2 import SpotifyClientCredentials, SpotifyOAuth
> 
> scope = "user-read-currently-playing"
> 
> sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))
> playback = sp.current_playback()
> print(playback)

and keep running into the following error:

> HTTP Error for GET to https://api.spotify.com/v1/me/player returned 401 due to Permissions missing
> Traceback (most recent call last):
>   File "/home/joe-linux/.pyenv/versions/venv-spotifriend/lib/python3.9/site-packages/spotipy/client.py", line 245, in _internal_call
>     response.raise_for_status()
>   File "/home/joe-linux/.pyenv/versions/venv-spotifriend/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.spotify.com/v1/me/player
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/joe-linux/Documents/GitHub Repos/spotifriend/.code/interface.py", line 14, in <module>
>     playback = sp.current_playback()
>   File "/home/joe-linux/.pyenv/versions/venv-spotifriend/lib/python3.9/site-packages/spotipy/client.py", line 1645, in current_playback
>     return self._get("me/player", market=market, additional_types=additional_types)
>   File "/home/joe-linux/.pyenv/versions/venv-spotifriend/lib/python3.9/site-packages/spotipy/client.py", line 291, in _get
>     return self._internal_call("GET", url, payload, kwargs)
>   File "/home/joe-linux/.pyenv/versions/venv-spotifriend/lib/python3.9/site-packages/spotipy/client.py", line 261, in _internal_call
>     raise SpotifyException(
> spotipy.exceptions.SpotifyException: http status: 401, code:-1 - https://api.spotify.com/v1/me/player:
>  Permissions missing, reason: None

I can't quite figure out what permissions are missing for this method call - I have SPOTIPY_CLIENT_ID, SPOTIPY_CLIENT_SECRET, and SPOTIPY_REDIRECT_URI set as environment variables.

Thanks in advance!

**Comment by joebonneau** [comment]
I'm realizing that maybe it's because I don't have a user specified, but I also don't see where to specify that.

**Comment by joebonneau** [comment]
Looks like I needed to use `util.prompt_for_user_token` instead of what I tried. Sorry for the spam and quick close!
