### ISSUE TITLE
"Permissions missing, reason: None" when trying the get the current playback.

### ISSUE THREAD

**Issue by thesadru** [plamere/spotipy#684]
I'm very sorry if I did something obviously wrong but I just can't figure this out.

I have this code that should get the current playback
```py
import spotipy
from spotipy.oauth2 import SpotifyOAuth

auth = SpotifyOAuth(
    '...', 
    '...', 
    'http://127.0.0.1:9090', 
    scope="user-read-currently-playing"
)
spotify = spotipy.Spotify(oauth_manager=auth)

pb = spotify.current_playback()
print(pb)
```
however, when I run it I get this error
```
HTTP Error for GET to https://api.spotify.com/v1/me/player returned 401 due to Permissions missing
Traceback (most recent call last):
  File "C:\Users\D\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 245, in _internal_call
    response.raise_for_status()
  File "C:\Users\D\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.spotify.com/v1/me/player

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\D\code\thesadru\culturebot\_test.py", line 13, in <module>
    pb = spotify.current_playback()
  File "C:\Users\D\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 1697, in current_playback
    return self._get("me/player", market=market, additional_types=additional_types)
  File "C:\Users\D\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 291, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "C:\Users\D\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 261, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 401, code:-1 - https://api.spotify.com/v1/me/player:
 Permissions missing, reason: None
```
My guess is that I'm just authenticating incorrectly, but I don't know where exactly I went wrong.

**Comment by thesadru** [comment]
So sorry, I actually just used the wrong scope.

**Comment by fluffy-cakes** [comment]
> So sorry, I actually just used the wrong scope.

what was the correct scope?

**Comment by thesadru** [comment]
No idea which one of these is currently doing the magic, but I have `user-read-recently-played,user-read-currently-playing,user-read-playback-state`
