### ISSUE TITLE
spotipy.recommendations() doesn't work for tracks

### ISSUE THREAD

**Issue by lohriialo** [plamere/spotipy#686]
`spotipy version = 2.18.0`

```
client_credentials_manager = SpotifyClientCredentials(SPOTIPY_CLIENT_ID, SPOTIPY_CLIENT_SECRET)
api = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
```

this works
```
random_artists = ["0C8ZW7ezQVs4URX5aX7Kqx", "1SupJlEpv7RS2tPNRaHViT"]
recommendation = api.recommendations(seed_artists=random_artists)
for track in recommendation['tracks']:
  print(track['name'], '-', track['artists'][0]['name'])
```

but this doesn't
```
random_tracks = ["-0kcet4aPpQ", "0RNDeBcIK00"]
recommendation = api.recommendations(seed_tracks=random_tracks)
for track in recommendation['tracks']:
  print(track['name'], '-', track['artists'][0]['name'])
```

or a combination of both doesn't work either
```
recommendation = api.recommendations(seed_artists=random_artists, seed_tracks=random_tracks)
for track in recommendation['tracks']:
  print(track['name'], '-', track['artists'][0]['name'])
```

Error is : 
```
HTTP Error for GET to https://api.spotify.com/v1/recommendations returned 400 due to invalid request
Traceback (most recent call last):
  File "/Users/test/PycharmProjects/test/venv/lib/python3.6/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/Users/test/PycharmProjects/test/venv/lib/python3.6/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/recommendations?limit=20&seed_tracks=-0kcet4aPpQ%2C05vC8lMeelg%2C0RNDeBcIK00

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/test/PycharmProjects/test/spotify/user_recommendation/get_user_recommendation_old.py", line 37, in <module>
    recommendation = sp.recommendations(seed_tracks=random_tracks)
  File "/Users/test/PycharmProjects/test/venv/lib/python3.6/site-packages/spotipy/client.py", line 1652, in recommendations
    return self._get("recommendations", **params)
  File "/Users/test/PycharmProjects/test/venv/lib/python3.6/site-packages/spotipy/client.py", line 291, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/Users/test/PycharmProjects/test/venv/lib/python3.6/site-packages/spotipy/client.py", line 266, in _internal_call
    headers=response.headers,
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/recommendations?limit=20&seed_tracks=-0kcet4aPpQ%2C05vC8lMeelg%2C0RNDeBcIK00:
 invalid request, reason: None
```

**Comment by stephanebruckert** [comment]
@lohriialo your `random_tracks` don't seem to be valid?

**Comment by lohriialo** [comment]
Hmm i'm not sure [docs says](https://spotipy.readthedocs.io/en/2.18.0/#spotipy.client.Spotify.recommendations) to give a list of tracks IDs, those are valid track IDs, so I just pass those tracks just as artist list

**Comment by lohriialo** [comment]
Aah ok, got it, my track IDs are invalid!

**Comment by lohriialo** [comment]
Thanks for the quick pointer!

**Comment by stephanebruckert** [comment]
no worries!
