### ISSUE TITLE
Error when trying to delete song from playlist using SpotifyOAuth

### ISSUE THREAD

**Issue by flancast90** [plamere/spotipy#724]
Hello, when trying to run the code below, I encounter an error:
```python
playlist_id = 'playlist id here'
song_id = 'id of song to remove'
index = 0
sp.playlist_remove_specific_occurrences_of_items(playlist_id, [{"uri":song_id,"positions":[index]}], snapshot_id=None)
```

I am authenticating as suggested in the documentation as follows:
```python
scope = "playlist-modify-public playlist-modify-private"

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(username='USERNAME', client_id="MY CLIENT ID", client_secret="MY CLIENT SECRET", redirect_uri="https://finnsoftware.net", scope=scope))
```

The error is as follows:
```python
Traceback (most recent call last):
  File "/home/flanc/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 559, in get_access_token
    response.raise_for_status()
  File "/home/flanc/.local/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SqeaPyCleanSpotify.py", line 104, in <module>
    require_approval()
  File "SqeaPyCleanSpotify.py", line 95, in require_approval
    get_user_action()
  File "SqeaPyCleanSpotify.py", line 45, in get_user_action
    clean_playlist_from_uri(playlist_id)
  File "SqeaPyCleanSpotify.py", line 50, in clean_playlist_from_uri
    playlist = sp.playlist(playlist_id, fields=None, market=None, additional_types=('track', ))
  File "/home/flanc/.local/lib/python3.8/site-packages/spotipy/client.py", line 617, in playlist
    return self._get(
  File "/home/flanc/.local/lib/python3.8/site-packages/spotipy/client.py", line 297, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/flanc/.local/lib/python3.8/site-packages/spotipy/client.py", line 221, in _internal_call
    headers = self._auth_headers()
  File "/home/flanc/.local/lib/python3.8/site-packages/spotipy/client.py", line 212, in _auth_headers
    token = self.auth_manager.get_access_token(as_dict=False)
  File "/home/flanc/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 565, in get_access_token
    self._handle_oauth_error(http_error)
  File "/home/flanc/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 146, in _handle_oauth_error
    raise SpotifyOauthError(
spotipy.oauth2.SpotifyOauthError: error: invalid_request, error_description: code must be supplied
```

Can someone explain what I am doing wrong?

**Comment by Peter-Schorn** [comment]
When you run this script, it should ask you to open a URL in your browser. When you open this URL, you should log in and then click the "agree" button. You should then be redirected to a URL that begins with your redirect URI (`https://finnsoftware.net`). Then, you should paste this URL back into the program in order to complete the authorization process. Is this what you're doing?

**Comment by flancast90** [comment]
Yes, @Peter-Schorn. I'm changing the redirect_url now, because I think javascript ```window.open()``` calls from the website are impacting the spotify redirect_url.

From what I read in the docs, it seems that you must include this redirect. Is there a way to bypass that redirect/url entry?

**Comment by Peter-Schorn** [comment]
> From what I read in the docs, it seems that you must include this redirect. Is there a way to bypass that redirect/url entry?

No, you cannot bypass this. You can read about the authorization process in detail [here](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow).

Are you running this as a local command-line script? If so, consider changing the redirect URI to `http://localhost:8080`.

**Comment by flancast90** [comment]
Thanks for your help, @Peter-Schorn, the issue was window.open() calls in the website js. As soon as I changed the authentication page to about:blank, it started working.
